#!/bin/bash
# Interactive configuration script for file-social deployment

set -e

cd "$(dirname "$0")/../.."

echo "📝 Let's configure your file-social deployment!"
echo ""

# Get server IP
while [ -z "$DEPLOY_HOST" ]; do
  read -p "Enter your server IP address: " DEPLOY_HOST
done

# Get domain (optional)
read -p "Enter your domain name (optional, press Enter to skip): " DEPLOY_DOMAIN

# Use root by default
DEPLOY_USER="root"
DEPLOY_PATH="/var/www/file-social"

# Create config file
cat > deploy/config.sh << EOF
#!/bin/bash
# file-social deployment configuration
# Generated by configure.sh

# SSH connection details
DEPLOY_USER="$DEPLOY_USER"
DEPLOY_HOST="$DEPLOY_HOST"
DEPLOY_PATH="$DEPLOY_PATH"

# Domain name (optional)
DEPLOY_DOMAIN="$DEPLOY_DOMAIN"
EOF

chmod +x deploy/config.sh

echo ""
echo "✅ Configuration saved!"
echo ""
echo "Server IP: $DEPLOY_HOST"
if [ -n "$DEPLOY_DOMAIN" ]; then
  echo "Domain: $DEPLOY_DOMAIN"
fi
echo ""

# Set up SSH key
echo "Setting up SSH access..."
echo ""

if [ ! -f ~/.ssh/id_rsa.pub ]; then
  echo "No SSH key found. Generating one..."
  ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
fi

echo "Copying SSH key to server..."
echo "(You'll need to enter your server password)"
echo ""

if command -v ssh-copy-id &> /dev/null; then
  ssh-copy-id -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST
else
  # Fallback for systems without ssh-copy-id
  cat ~/.ssh/id_rsa.pub | ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys && chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys"
fi

echo ""
echo "✅ SSH access configured!"
echo ""
echo "Setting up server..."
echo ""

# Run setup script
./deploy/ubuntu-24/setup.sh

echo ""
echo "✅ All done! Your server is ready."
echo ""
echo "Next step: npm run deploy"

