#!/bin/bash
# Interactive configuration script for file-social deployment

set -e

cd "$(dirname "$0")/.."

echo "📝 Let's configure your file-social deployment!"
echo ""

# Get server IP
while [ -z "$DEPLOY_HOST" ]; do
  read -p "Enter your server IP address: " DEPLOY_HOST
done

# Get domain (optional)
read -p "Enter your domain name (optional, press Enter to skip): " DEPLOY_DOMAIN

# Use root by default
DEPLOY_USER="root"
DEPLOY_PATH="/var/www/file-social"

# Create config file
cat > deploy/config.sh << EOF
#!/bin/bash
# file-social deployment configuration
# Generated by configure.sh

# SSH connection details
DEPLOY_USER="$DEPLOY_USER"
DEPLOY_HOST="$DEPLOY_HOST"
DEPLOY_PATH="$DEPLOY_PATH"

# Domain name (optional)
DEPLOY_DOMAIN="$DEPLOY_DOMAIN"
EOF

chmod +x deploy/config.sh

echo ""
echo "✅ Configuration saved!"
echo ""
echo "Server IP: $DEPLOY_HOST"
if [ -n "$DEPLOY_DOMAIN" ]; then
  echo "Domain: $DEPLOY_DOMAIN"
fi
echo ""
echo "Next steps:"
echo "1. Make sure you can SSH to your server: ssh root@$DEPLOY_HOST"
echo "2. Run: npm run deploy:setup"

