#!/bin/bash
# Interactive configuration script for file-social deployment (Raspberry Pi)

set -e

cd "$(dirname "$0")/../.."

echo "📝 Let's configure your Raspberry Pi deployment!"
echo ""

# Get username
read -p "Enter your Pi username (default: pi): " DEPLOY_USER
DEPLOY_USER=${DEPLOY_USER:-pi}

# Get server IP or hostname
while [ -z "$DEPLOY_HOST" ]; do
  read -p "Enter your Pi IP address or hostname (e.g., raspberrypi.local): " DEPLOY_HOST
done

# Get server port
read -p "Enter Node.js server port (default: 7650): " SERVER_PORT
SERVER_PORT=${SERVER_PORT:-7650}

DEPLOY_PATH="/var/www/file-social"

# Create config file
cat > deploy/config.sh << EOF
#!/bin/bash
# file-social deployment configuration
# Generated by configure.sh

# SSH connection details
DEPLOY_USER="$DEPLOY_USER"
DEPLOY_HOST="$DEPLOY_HOST"
DEPLOY_PATH="$DEPLOY_PATH"

# Server port
SERVER_PORT="$SERVER_PORT"
EOF

chmod +x deploy/config.sh

echo ""
echo "✅ Configuration saved!"
echo ""
echo "Pi address: $DEPLOY_HOST"
echo "Server port: $SERVER_PORT"
echo ""

# Set up SSH key
echo "Setting up SSH access..."
echo ""

if [ ! -f ~/.ssh/id_rsa.pub ]; then
  echo "No SSH key found. Generating one..."
  ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
fi

echo "Copying SSH key to server..."
echo "(You'll need to enter your server password)"
echo ""

if command -v ssh-copy-id &> /dev/null; then
  ssh-copy-id -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST
else
  # Fallback for systems without ssh-copy-id
  cat ~/.ssh/id_rsa.pub | ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys && chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys"
fi

echo ""
echo "✅ SSH access configured!"
echo ""
echo "Setting up server..."
echo ""

# Run setup script
./deploy/pi-trixie/setup.sh

echo ""
echo "✅ All done! Your server is ready."
echo ""
echo "Next step: npm run pi:deploy"

